name: Build and Publish Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.6.1'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies with pnpm
        run: pnpm install

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Docker Buildx
        run: |
          docker buildx create --use --name mybuilder
          docker buildx inspect mybuilder --bootstrap

      - name: Build and push Docker images
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --tag ghcr.io/$REPO_NAME:latest \
            --tag ghcr.io/$REPO_NAME:${{ github.sha }} \
            --push .

      - name: Post Build Info
        run: |
          echo "🎉 Docker images for $REPO_NAME have been built and pushed successfully!"
          echo "🖥️  Platforms: linux/amd64, linux/arm64, linux/arm/v7"
          echo "📝  Tags:"
          echo "     - ghcr.io/$REPO_OWNER/$REPO_NAME:latest"
          echo "     - ghcr.io/$REPO_OWNER/$REPO_NAME:${{ github.sha }}"

      - name: Print Docker version
        run: docker version
